### PR TITLE
fixed ur link victor

### PR DESCRIPTION
**Pull request by tjhorner**
merge this PR

### CODE REVIEW

**Comment by pixelyunicorn** [comment]
:+1: https://www.youtube.com/watch?v=ji0tpUM8DfU

**Comment by tjhorner** [comment]
what the fuck does that rarity clip have to do with anything

original text in case victor edits it (he will probably edit this too):

> :+1: https://www.youtube.com/watch?v=ji0tpUM8DfU

**Comment by pixelyunicorn** [comment]
ok tj
image

**Comment by tjhorner** [comment]
why I said

> (he will probably edit this too)

**Pull request merged**
